// adding required modulesconst express = require('express')const mongoose = require('mongoose')const path = require('path')const cors = require('cors')const passport = require('passport')const bodyparser = require('body-parser')const users = require('./routes/users')const config = require('./config/database')
const app = express()
//connecting Databasemongoose.connect(config.database)
mongoose.connection.on('connected',() => {    console.log('Connected to server')})
//errormongoose.connection.on('error',(err) => {    console.log('Sorry error =>' +err)})
//Adding Coreapp.use(cors())
//Bodyparserapp.use(bodyparser.json())
//Putting Static Filesapp.use(express.static(path.join(__dirname,'angular')))
//Routingapp.use('/users',users)
//passport Middleware app.use(passport.initialize());app.use(passport.session())require('./config/passport')(passport)
//Setting Home Routeapp.get('/home',function(req,res){    res.send('Welcome to Homepage')})
//Starting serverapp.listen(4000,() => {    console.log('Server started')})
